language: python

env:
 global:
  - GH_REF: github.com/NewFuture/NKUWLAN.git

script:
  - git clone --depth=1 -b build "https://${GH_REF}" build
  - python build.py build/nkuwlan.py

after_script:
  - cd ./build
  - git config user.name "New Future (auto build)"
  - git config user.email "github@newfuture.cc"
  - git commit -am "Auto Update from master"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" build:build

branches:
  only:
    - master
