language: python

git:
  depth: 1

env:
 global:
  - GH_REF: "NewFuture/NKUWLAN.git"
  - BUILD_PATH: "build/"
  - NAME: "From Travis CI"
  - EMAIL: "github@newfuture.cc"

before_script:
  - echo $ID_RSA >t.rsa && base64 -d t.rsa>~/.ssh/id_rsa && rm t.rsa && chmod 600 ~/.ssh/id_rsa
  - git clone --depth=1 -b build "git@github.com:${GH_REF}"  ${BUILD_PATH}

script:
  - python build.py ${BUILD_PATH}nkuwlan.py
  # compile to check syntax
  - python -m py_compile ${BUILD_PATH}nkuwlan.py

after_success:
  - cd ${BUILD_PATH} && eval $(ssh-agent)
  - git config user.name "$NAME" && git config user.email "$EMAIL"
  - git commit -am "$(curl -sL https://newfuture.github.io/emoji/e.sh|bash) Auto build from master $(curl -sL https://newfuture.github.io/emoji/e.sh|bash)"
  - git push -f "git@github.com:${GH_REF}" build:build

branches:
  only:
    - master
