language: python

git:
  depth: 1

env:
 global:
  - GH_REF: "github.com/NewFuture/NKUWLAN.git"
  - BUILD_PATH: "build/"
  - GIT_COMMITTER_NAME: "From Travis CI"
  - COMMIT_AUTHOR_EMAIL: "github@newfuture.cc"
  - emojis: "(🐶 🐺 🐱 🐭 🐹 🐰 🐸 🐯 🐨 🐻 🐷 🐮 🐵 🐼 🐧 🐍 🐢 🐙 🐠 🐳 🐬 🐥)"

before_script:
  - git clone --depth=1 -b build "https://${GH_REF}"  ${BUILD_PATH}

script:
  - python build.py ${BUILD_PATH}nkuwlan.py
  # compile to check syntax
  - python -m py_compile ${BUILD_PATH}nkuwlan.py

after_success:
  - cd  ${BUILD_PATH}
  - git commit -am "${emojis[$RANDOM % 22]} Auto Update from master"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" build:build

branches:
  only:
    - master
